name: Brian Storti
meta_description: "blog posts written by Brian Storti"

markdown: redcarpet
highlighter: pygments
logo: false
permalink: /:title
port: 4567

# Details for the RSS feed generator
url:            'brianstorti.github.io'
author:         'Brian Storti'
