name: Brian Storti
meta_description: "Brian Storti works at ThoughtWorks, and here he writes about Ruby, Vim, UNIX and other topics related to software development."

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge
logo: false
permalink: /:title/
port: 4567

# Details for the RSS feed generator
url:            'www.brianstorti.com'
author:         'Brian Storti'

social:
  linkedin: 'http://linkedin.com/in/brianstorti'
  github: 'http://github.com/brianstorti'
  twitter: 'http://twitter.com/brianstorti'
  email: 'mailto:btstorti@gmail.com'
  rss: '/feed/atom.xml'
